name: Tech-flow Project Pipeline
run-name: Tech-flow Project Pipeline tested by ${{ github.actor }} on ${{ github.ref }}
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Display Python version
        run: |
          python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest
      - name: Stop the pipeline if tests fail
        if: failure()
        run: |
          echo "Tests failed, stopping the pipeline."

  push-to-docker:
    runs-on: ubuntu-latest

    needs: build
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Log in to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DockerHub_Password}}
      - name: build app
        run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/tech-flow:latest .
      - name: tag image as current sha
        run: docker tag ${{secrets.DOCKERHUB_USERNAME}}/tech-flow:latest ${{secrets.DOCKERHUB_USERNAME}}/tech-flow:${{ github.sha }}
      - name: verify build
        run: docker images # | grep ${{secrets.DOCKERHUB_USERNAME}}/teck-flow
      - name: push to Dockerhub
        run: |
            docker push ${{secrets.DOCKERHUB_USERNAME}}/tech-flow:latest
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/tech-flow:${{ github.sha }}
      
  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: push-to-docker

    steps:
      - name: ssh to ec2
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          # port: ${{ secrets.EC2_PORT }}
          script: |
            # 1 Log into Docker Hub on the remote server
            echo "${{ secrets.DOCKERHUB_PASSWORD}}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            docker tag ${{secrets.DOCKERHUB_USERNAME}}/tech-flow:latest ${{secrets.DOCKERHUB_USERNAME}}/tech-flow:previous_stable
            docker push  ${{secrets.DOCKERHUB_USERNAME}}/tech-flow:previous_stable
            docker pull ${{secrets.DOCKERHUB_USERNAME}}/tech-flow:latest
            docker stop tech-flow-app
            docker rm tech-flow-app
            docker run -d -p 5000:5000 --name tech-flow-app ${{secrets.DOCKERHUB_USERNAME}}/tech-flow:latest

      - name: Send status email
        uses: dawidd6/action-send-mail@v4 # Always check for the latest major version
        with:
          # Mail server settings
          server_address: smtp.gmail.com
          server_port: 465

          username: ${{secrets.EMAIL_USERNAME}}
          password: ${{secrets.EMAIL_APP_PASSWORD}}

          subject: Github 
          to: "naapholei@gmail.com"
          from: "Antoinette Tettey <naafolei@gmail.com>"
          body: |
            The build job for ${{ github.repository }} completed.
            Status: ${{ job.status }}
            View log: https://github.com{{ github.repository }}/actions/runs/${{ github.run_id }}

